### ISSUE TITLE
Problem with google drive

### ISSUE THREAD

**Issue by mesteryui** [nift4/microg_installer_revived#120] opened 2024-02-13 01:04 UTC
When I use the app without microG installer, but the apks of microG installed by the official web, Google Drive works but with microG installer doesn't work

**Comment by mesteryui** [comment] 2024-02-13 01:07
I discover that this problem can be solved using the same method that in the #119 issue

**Comment by nift4** [comment] 2024-02-13 11:27
the root cause is related to bug 72, so if you solved the problem, i will close this one

**Closed by nift4** 2024-02-13 11:27 UTC
