### ISSUE TITLE
Permissions mising on Android 14

### ISSUE THREAD

**Issue by uvww** [nift4/microg_installer_revived#119] opened 2024-02-12 19:12 UTC
Custom rom: Crdroid 10.2 based on Android 14

While using android 13, there was no problem about installer. I upgraded my system to android 14 without clean flashing and there was still no problem. But when I clean flashed system and used this installer all permissions were missing on self-check. I was able to allow permissions except SMS and foreground location. It simply didn't prompt to allow permissions. I think the problem is either microg itself or installer but not sure. Also wonder are these permissions important microg to work properly.

**Comment by nift4** [comment] 2024-02-12 19:14
I am aware you have microG already installed, and the newest version, too - however, to fix this issue, you need to download & install this microG APK: https://github.com/nift4/microg_installer_revived/raw/master/system/priv-app/microG/microG.apk

After doing that, you'll be able to grant these permissions.

**Comment by mesteryui** [comment] 2024-02-13 01:02
I have a similar problem but when I install the app in my device the app doesnt' allow me to add some permissions and I have to download the app microG install it and after that add the permissions, but this without microG installer revived installed

**Comment by nift4** [comment] 2024-02-13 11:28
the root cause is related to bug 72, closing

**Closed by nift4** 2024-02-13 11:28 UTC

**Comment by uvww** [comment] 2024-02-13 14:34
> I am aware you have microG already installed, and the newest version, too - however, to fix this issue, you need to download & install this microG APK: https://github.com/nift4/microg_installer_revived/raw/master/system/priv-app/microG/microG.apk
> 
> After doing that, you'll be able to grant these permissions.

Will using official microg apk also work? Did you specifally patched this apk?

**Comment by nift4** [comment] 2024-02-13 17:55
this is the official, unpatched microg apk, i just send out my link to avoid confusion based on what version to install

**Comment by nift4** [comment] 2024-02-28 15:11
Have you tried flashing 3.4.2 twice?

**Comment by auvio323** [comment] 2024-03-03 06:58
> > the root cause is related to bug 72, closing
> 
> I think it's not. I'm using LineageOS 21, Android 14, Mi A3 and upon installing this module (that is I'm not updating but installing for the first time) I'm able to give all permissions except for Always on location and SMS. Flashing v3.4.1 fixes everything (all permissions are auto set after rebooting).

Same exact thing happened to me, Im using Oneplus 9 Pro (lemonadep) on crDroid 10.2 (A14). I reinstalled v.3.4.2 several times, it was only when I flashed v3.4.1 my permissions came back.

I also remember before I updated to crDroid 10.2 and I was on crDroid 9.10 (A13) I was using v3.4.1 and didn't update to 3.4.2 and my permissions were working fine.
