### ISSUE TITLE
Update GmsCore

### ISSUE THREAD

**Issue by aegis965** [nift4/microg_installer_revived#11] opened 2020-07-30 16:54 UTC
A new [release](https://github.com/microg/android_packages_apps_GmsCore/releases/tag/v0.2.11.202414) of GmsCore is available.

**Comment by nift4** [comment] 2020-07-30 17:20
I already saw that but I cannot try it out myself since I'm no longer using microG. It would be great if you could test an update.

**Comment by aegis965** [comment] 2020-07-31 05:25
Sure, Happy to.

**Comment by thomas2403** [comment] 2020-07-31 09:06
If you like to have one more for testing, I could do that too.

**Comment by nift4** [comment] 2020-07-31 10:26
[microG_Installer_Revived.zip](https://github.com/nift4/microg_installer_revived/files/5006512/microG_Installer_Revived.zip)

**Comment by thomas2403** [comment] 2020-07-31 20:16
My phone got into a boot loop after updating. I tried the module again with a clean flash, same result. I was using 1.3.0 before, no problems so far beside the known issues with Android 10. 
The new version of microg itself is working, I have tested it with MinMicroG (https://github.com/FriendlyNeighborhoodShane/MinMicroG). But like NanoDroid, that brings some unwanted apps. 
Let's see, what result @aegis965 will get.

**Comment by nift4** [comment] 2020-07-31 20:28
The same. The bootloop is inside android by design and exactly that reason I couldn't just swap out the apk. Can you please get logfiles from recovery at /data/system/dropbox after bootlooping?

**Comment by thomas2403** [comment] 2020-08-01 11:39
All files from  /data/system/dropbox
[dropbox.zip](https://github.com/thomas2403/logfiles/raw/master/dropbox.zip)

**Comment by nift4** [comment] 2020-08-02 07:22
[microG_Installer_Revived.zip](https://github.com/nift4/microg_installer_revived/files/5011773/microG_Installer_Revived.zip)

**Comment by thomas2403** [comment] 2020-08-02 08:35
Almost perfect. Just one little thing, I can't get the permission for background location, You can't enable it in the UI like the other ones. It's not getting enabled when you touch it. Maybe something with the permission file?

![Screenshot_20200802-101423_microG_Services_Core](https://user-images.githubusercontent.com/17723660/89119061-973bdb80-d4ab-11ea-8e74-e1fa15563cc4.png)

**Comment by nift4** [comment] 2020-08-02 08:55
Try doing this in Settings

**Comment by DocSniper** [comment] 2020-08-02 09:06
The ACCESS_BACKGROUND_LOCATION thing seems to be a known issue, see: https://github.com/microg/android_packages_apps_GmsCore/issues/1099

**Comment by nift4** [comment] 2020-08-02 09:22
That means it's an microG bug that will fixed with an update so I can leave this issue straightup open :/

**Comment by aegis965** [comment] 2020-08-02 11:10
Sorry I'm late to the party... Everything works fine other than the UNDEFINED permission. Can confirm it is also an issue in MinMicroG.

**Comment by thomas2403** [comment] 2020-08-02 14:40
Yes and no. For me it is clear now, that this is a microG bug. On the other hand, I installed MinMicroG today (clean flash) and I didn't have to do the modifications described here https://github.com/microg/android_packages_apps_GmsCore/issues/1099

But NLP is not really working for me. Some apps are OK (SatStat shows the blue circle some times), but other ones don't get any location. Again, this is clearly a microG issue.

**Comment by nift4** [comment] 2020-09-19 17:20
Please test this version with microG 0.2.12
[microG_Installer_Revived.zip](https://github.com/nift4/microg_installer_revived/files/5250256/microG_Installer_Revived.zip)

**Comment by nift4** [comment] 2020-09-19 17:20
if it boots I get it to the magisk repo

**Comment by DocSniper** [comment] 2020-09-19 18:01
Great, runs perfectly. 😃
Thanks

**Comment by nift4** [comment] 2020-09-19 18:07
thanks for testing everyone, the new version is released

**Closed by nift4** 2020-09-19 18:07 UTC
