### ISSUE TITLE
Can't install real play store (Didn't find class "androidx.startup.InitializationProvider") 

### ISSUE THREAD

**Issue by LeVraiRoiDHyrule** [nift4/microg_installer_revived#159] opened 2024-09-02 21:44 UTC
Hi,

I am trying to use this installer with real play store, using the method explained in the Readme. I've correctly added a play store apk, renamed it Phonesky.apk, and installed the addon. It correctly finds it and install it.

But then, regularly, the real play store crashes with the following logs:
https://paste.crdroid.net/LFyvmP

The error is the following: Didn't find class "androidx.startup.InitializationProvider"

Would you have an idea of what could be wrong?
I would really appreciate some help because I need the real play store to get play integrity to work, and this is required since a few weeks for my bank app so it could become a big problem.

Thanks in advance for any answer and have a nice day

**Comment by nift4** [comment] 2024-09-02 22:00
This is caused by applying root hiding (Magisk Hide, DenyList, SafetyNet fix / Play Integrity fix and many other things) to Play Store. It creates a chicken egg problem: APK is added by Magisk, but Play Store can't see Magisk changes => Play Store can't see it's own APK. The easiest fix is to install the apk as user apk in addition, and system will see apk on partition and is happy and Play Store won't crash because it has userdata APK.

**Comment by nift4** [comment] 2024-09-06 15:45
should be fixed by https://github.com/nift4/microg_installer_revived/releases/tag/v4.0.0-0

**Closed by nift4** 2024-09-06 15:45 UTC
